version: '3.4'

services:  
  hostocean.api:
    image: hostocean.api:latest
    build:
      context: .
      dockerfile: HostOcean.Api/Dockerfile
    depends_on:
      - data.sql

  data.sql:
    image: microsoft/mssql-server-linux:latest

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    container_name: elasticsearch
    ports:
     - "9200:9200"
    volumes:
     - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
     - docker-network

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.4
    container_name: kibana
    ports:
     - "5601:5601"
    depends_on:
     - elasticsearch
    networks:
     - docker-network

networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data: